name = "ClimbDataEval"
uuid = "20004f9b-6fcd-4a36-bc8b-a5c8917d23ad"
authors = ["Johannes Ultsch"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
